apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: web
  name: web-controller
spec:
  replicas: 3
  selector:
    name: web
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - image: <location for image from Dockerfile>
        name: web
        env:
        - name: "DBHOST"
          value: "mongodb://mongo-0.mongo,mongo-1.mongo,mongo-2.mongo:27017"
        ports:
        - containerPort: 3000
