apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-nfs-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
#i used nfs so if you did, use your settings
#provisioner: mylab.com/nfs
provisioner: <you can change to your settings>
parameters:
  archiveOnDelete: "false"
